import { createClient } from "https://esm.sh/@supabase/supabase-js@2.57.4";
const supabase=createClient("https://bowvuafbszouqimilytd.supabase.co","sb_publishable_lz5Tf7Xfkz9KTPWjNtvtzQ_Xo9yVAFG");
let session=null,role=null;const $=(selector)=>document.querySelector(selector);const esc=(value)=>String(value??"").replace(/[&<>"']/g,(character)=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[character]));
function show(html,admin=false){$("#modalContent").innerHTML=html;$("#modal").className=admin?"modal adminModal":"modal";$("#modalWrap").hidden=false}function close(){$("#modalWrap").hidden=true;if(location.hash)history.replaceState(null,"",location.pathname)}
function authView(){show(`<span class="kpEyebrow">ЛИЧНЫЙ КАБИНЕТ</span><h2>Вход в систему</h2><p class="modalLead">Используйте корпоративную или личную электронную почту.</p><label>Электронная почта<input id="email" type="email" placeholder="name@example.com"></label><label>Пароль<input id="password" type="password" placeholder="Не менее 6 символов"></label><div class="formActions"><button class="primary" id="login">Войти</button><button class="secondary" id="signup">Создать доступ</button></div><p class="formMessage" id="msg" hidden></p>`);const run=async(create)=>{const email=$("#email").value,password=$("#password").value,result=create?await supabase.auth.signUp({email,password}):await supabase.auth.signInWithPassword({email,password});$("#msg").hidden=false;$("#msg").textContent=result.error?result.error.message:(create&&!result.data.session?"Подтвердите почту по ссылке в письме.":"Вход выполнен.");if(result.data.session){session=result.data.session;close();await init();await cabinet()}};$("#login").onclick=()=>run(false);$("#signup").onclick=()=>run(true)}
function registerView(){show(`<form id="regForm"><span class="kpEyebrow">РЕГИСТРАЦИЯ</span><h2>Школа корпоративного волонтёрства</h2><div class="formGrid"><label>Имя<input name="first_name" required></label><label>Фамилия<input name="last_name" required></label><label>Телефон<input name="phone" required></label><label>Подразделение<input name="department" required></label><label>Регион<input name="region" required></label><label>Команда<input name="team_name"></label></div><label>Комментарий<textarea name="comment"></textarea></label><div class="formActions"><button class="primary">Отправить заявку</button><button type="button" class="secondary" id="logout">Выйти</button></div><p class="formMessage" id="msg" hidden></p></form>`);$("#logout").onclick=async()=>{await supabase.auth.signOut();session=null;close();init()};$("#regForm").onsubmit=async(event)=>{event.preventDefault();const form=Object.fromEntries(new FormData(event.target));const profile={first_name:form.first_name,last_name:form.last_name,phone:form.phone,department:form.department,region:form.region,email:session.user.email};const {error:profileError}=await supabase.from("profiles").update(profile).eq("id",session.user.id);const {error}=profileError?{error:profileError}:await supabase.from("registrations").insert({user_id:session.user.id,event_id:"volunteer-school-2026",discipline:"Корпоративное волонтёрство",team_name:form.team_name||null,comment:form.comment||null,health_confirmed:true,status:"submitted"});$("#msg").hidden=false;$("#msg").textContent=error?error.message:"Готово! Ваша заявка принята."}}
async function adminView(){const {data=[]}=await supabase.from("registrations").select("id,discipline,team_name,status,created_at,profiles(first_name,last_name,email,department,region,phone)").order("created_at",{ascending:false});show(`<div class="adminHead"><div><span class="kpEyebrow">БЫСТРАЯ ПАНЕЛЬ</span><h2>Регистрации на события</h2></div><button class="secondary" id="logout">Выйти</button></div><div class="adminStats"><div><strong>${data.length}</strong><span>всего заявок</span></div><div><strong>${data.filter((row)=>row.status==="submitted").length}</strong><span>новых</span></div><div><strong>${new Set(data.map((row)=>row.profiles?.region).filter(Boolean)).size}</strong><span>регионов</span></div></div><div class="tableWrap"><table><thead><tr><th>Участник</th><th>Контакты</th><th>Подразделение</th><th>Направление</th><th>Статус</th></tr></thead><tbody>${data.map((row)=>`<tr><td><b>${esc(row.profiles?.last_name)} ${esc(row.profiles?.first_name)}</b><small>${esc(row.profiles?.region)}</small></td><td>${esc(row.profiles?.email)}<small>${esc(row.profiles?.phone)}</small></td><td>${esc(row.profiles?.department||"—")}</td><td>${esc(row.discipline||"—")}</td><td><span class="status">${row.status==="submitted"?"Новая":esc(row.status)}</span></td></tr>`).join("")}</tbody></table>${data.length?"":'<p class="emptyState">Пока нет регистраций.</p>'}</div>`,true);$("#logout").onclick=async()=>{await supabase.auth.signOut();session=null;close();init()}}
async function cabinet(){if(!session)return authView();if(role==="admin")return adminView();return registerView()}
async function init(){({data:{session}}=await supabase.auth.getSession());if(session){const {data}=await supabase.from("profiles").select("role").eq("id",session.user.id).single();role=data?.role||"participant"}else role=null;$("#cabinet").textContent=session?(role==="admin"?"Админ-панель":"Мои заявки"):"Личный кабинет"}
$("#menu").onclick=()=>$(".kpHeader>nav").classList.toggle("open");$("#cabinet").onclick=cabinet;$("#eventRegister").onclick=()=>session?registerView():authView();$("#modalClose").onclick=close;$("#modalWrap").onclick=(event)=>event.target.id==="modalWrap"&&close();
const observer=new IntersectionObserver((entries)=>entries.forEach((entry)=>{if(entry.isIntersecting){entry.target.classList.add("is-visible");observer.unobserve(entry.target)}}),{threshold:.08});document.querySelectorAll(".reveal").forEach((node)=>observer.observe(node));
await init();if(location.hash==="#login")authView();if(location.hash==="#register")session?registerView():authView();
