create table public.page_views (
  id bigint generated by default as identity primary key,
  path text not null check (char_length(path) between 1 and 240 and path like '/%'),
  page_title text not null default '' check (char_length(page_title) <= 200),
  visitor_id uuid not null,
  session_id uuid not null,
  referrer_host text check (referrer_host is null or char_length(referrer_host) <= 200),
  visited_at timestamptz not null default now()
);

alter table public.page_views enable row level security;

revoke all on table public.page_views from anon, authenticated;
grant insert on table public.page_views to anon, authenticated;
grant select on table public.page_views to authenticated;
grant usage, select on sequence public.page_views_id_seq to anon, authenticated;

create policy "Visitors record page views"
on public.page_views
for insert
to anon, authenticated
with check (
  path like '/%'
  and path not like '%://%'
  and char_length(path) <= 240
  and char_length(page_title) <= 200
  and (referrer_host is null or char_length(referrer_host) <= 200)
);

create policy "Admins read site analytics"
on public.page_views
for select
to authenticated
using (public.is_admin());

create index page_views_visited_at_idx on public.page_views (visited_at desc);
create index page_views_path_idx on public.page_views (path);
create index page_views_visitor_id_idx on public.page_views (visitor_id);

create or replace function public.get_site_analytics()
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  analytics jsonb;
begin
  if not public.is_admin() then
    raise exception 'Administrator access required' using errcode = '42501';
  end if;

  select jsonb_build_object(
    'summary', jsonb_build_object(
      'total_views', count(*),
      'unique_visitors', count(distinct visitor_id),
      'sessions', count(distinct session_id),
      'today_views', count(*) filter (
        where visited_at >= date_trunc('day', timezone('Asia/Almaty', now())) at time zone 'Asia/Almaty'
      ),
      'seven_day_views', count(*) filter (where visited_at >= now() - interval '7 days')
    ),
    'pages', coalesce((
      select jsonb_agg(to_jsonb(page_stats) order by page_stats.views desc, page_stats.path)
      from (
        select
          path,
          max(page_title) as page_title,
          count(*) as views,
          count(distinct visitor_id) as visitors,
          max(visited_at) as last_visit
        from public.page_views
        group by path
      ) as page_stats
    ), '[]'::jsonb),
    'daily', coalesce((
      select jsonb_agg(to_jsonb(day_stats) order by day_stats.day)
      from (
        select
          to_char(days.day, 'YYYY-MM-DD') as day,
          count(page_views.id) as views,
          count(distinct page_views.visitor_id) as visitors
        from generate_series(
          date_trunc('day', timezone('Asia/Almaty', now())) - interval '13 days',
          date_trunc('day', timezone('Asia/Almaty', now())),
          interval '1 day'
        ) as days(day)
        left join public.page_views
          on date(timezone('Asia/Almaty', page_views.visited_at)) = date(days.day)
        group by days.day
      ) as day_stats
    ), '[]'::jsonb),
    'recent', coalesce((
      select jsonb_agg(to_jsonb(recent_views) order by recent_views.visited_at desc)
      from (
        select path, page_title, visited_at
        from public.page_views
        order by visited_at desc
        limit 20
      ) as recent_views
    ), '[]'::jsonb)
  )
  into analytics
  from public.page_views;

  return analytics;
end;
$$;

revoke all on function public.get_site_analytics() from public, anon;
grant execute on function public.get_site_analytics() to authenticated;

comment on table public.page_views is
  'Privacy-friendly page view events. Stores pseudonymous browser and session identifiers, never IP addresses.';

